on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Create tag artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.ref_name}}
        path: Release
        run: echo ${{github.ref_name}}