name: release

on:
  push
    tags:
      - 'v*'
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pyTooling/Actions/releaser@r0
        with:
          USERNAME: MaxChangInnodisk
          token: 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
          tag: {{ github.ref }}
          files: ${{ github.event.repository.name }}-{{ github.ref }}.zip
